from __future__ import annotations

from aurora_agent_core.llm.zai_client import ZaiChatResult
from aurora_agent_core.miners.dataset_miner_graph import DatasetMinerGraph


class FakeResponse:
    def __init__(self, payload):
        self.payload = payload

    def raise_for_status(self) -> None:
        return None

    def json(self):
        return self.payload


class FakeClient:
    def __init__(self, *args, **kwargs):
        pass

    def __enter__(self):
        return self

    def __exit__(self, *args):
        return False

    def post(self, url, json):
        return FakeResponse(
            {
                "vulns": [
                    {
                        "id": "GHSA-test-0001",
                        "summary": "Test Web3 vulnerability",
                        "details": "A real OSV-style vulnerability record.",
                        "aliases": ["CVE-2099-0001"],
                        "published": "2099-01-01T00:00:00Z",
                        "modified": "2099-01-02T00:00:00Z",
                        "database_specific": {
                            "severity": "HIGH",
                            "cwe_ids": ["CWE-20"],
                        },
                        "references": [
                            {"type": "ADVISORY", "url": "https://example.com/advisory"},
                        ],
                    }
                ]
            }
        )


def test_dataset_miner_uses_osv_records(monkeypatch, tmp_path) -> None:
    monkeypatch.setattr("aurora_agent_core.miners.dataset_miner_graph.httpx.Client", FakeClient)
    result = DatasetMinerGraph().run(
        {
            "task_id": "task_osv_test",
            "task_type": "dataset_generation",
            "title": "Web3 漏洞数据集",
            "goal": "构建 Web3 漏洞数据集",
            "requirements": ["仅真实公开来源"],
            "constraints": ["仅公开来源"],
            "output_format": "jsonl",
            "target_size": 1,
            "source_scope": ["osv"],
        },
        output_dir=tmp_path / "dataset",
    )
    assert result["status"] == "completed"
    assert result["summary"]["records"] == 1
    dataset_text = (tmp_path / "dataset" / "dataset.jsonl").read_text(encoding="utf-8")
    assert "GHSA-test-0001" in dataset_text
    assert '"synthetic_mvp": false' in dataset_text


def test_dataset_miner_does_not_keep_public_web_when_osv_is_requested(monkeypatch, tmp_path) -> None:
    monkeypatch.setattr("aurora_agent_core.miners.dataset_miner_graph.httpx.Client", FakeClient)
    result = DatasetMinerGraph().run(
        {
            "task_id": "task_osv_sources_test",
            "task_type": "dataset_generation",
            "title": "Web3 漏洞数据集",
            "goal": "构建 Web3 漏洞数据集",
            "requirements": ["仅真实公开来源"],
            "constraints": ["仅公开来源"],
            "output_format": "jsonl",
            "target_size": 1,
            "source_scope": ["osv", "public_web"],
        },
        output_dir=tmp_path / "dataset",
    )
    assert result["summary"]["sources_used"] == 5


def test_dataset_miner_uses_zai_for_synthetic_records_and_report(monkeypatch, tmp_path) -> None:
    calls = []

    def fake_llm(messages, *args, **kwargs):
        calls.append(messages)
        system = messages[0]["content"]
        if "report writer" in system:
            return ZaiChatResult(
                content="# Dataset Report\n\n- Generated by mocked Z.ai.",
                usage={
                    "provider": "zai",
                    "model": "glm-test",
                    "base_url": "https://example.test",
                    "prompt_tokens": 30,
                    "completion_tokens": 10,
                    "total_tokens": 40,
                },
            )
        return ZaiChatResult(
            content='[{"title":"Reentrancy synthetic case","category":"reentrancy","prompt":"Analyze the callback risk.","answer":"The state update happens after an external call.","reasoning":"This matches a reentrancy pattern.","source_url":"https://github.com/search?q=reentrancy"}]',
            usage={
                "provider": "zai",
                "model": "glm-test",
                "base_url": "https://example.test",
                "prompt_tokens": 50,
                "completion_tokens": 20,
                "total_tokens": 70,
            },
        )

    monkeypatch.setattr("aurora_agent_core.miners.dataset_miner_graph.call_zai_chat_with_usage", fake_llm)

    result = DatasetMinerGraph().run(
        {
            "task_id": "task_dataset_llm_test",
            "task_type": "dataset_generation",
            "metadata": {"use_llm": True},
            "title": "Web3 漏洞数据集",
            "goal": "构建 1 条 Web3 漏洞 synthetic 数据集",
            "requirements": ["覆盖重入"],
            "constraints": ["仅公开来源"],
            "output_format": "jsonl",
            "target_size": 1,
            "source_scope": ["github"],
        },
        output_dir=tmp_path / "dataset_llm",
    )

    assert len(calls) == 2
    assert result["status"] == "completed"
    assert result["summary"]["records"] == 1
    assert result["usage"]["extraction_method"] == "zai_synthetic_generation"
    assert result["usage"]["llm"]["calls"] == 2
    assert result["usage"]["llm_total_tokens"] == 110
    dataset_text = (tmp_path / "dataset_llm" / "dataset.jsonl").read_text(encoding="utf-8")
    assert '"model_generated": true' in dataset_text
    assert "Reentrancy synthetic case" in dataset_text
